name: Deploy to neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate sitemap.json
        run: python build_sitemap.py

      - name: Commit sitemap.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add public/data/sitemap.json
          git commit -m "Update sitemap.json" || echo "No changes"
          git push

      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: false
          dist_dir: public
